In [165]:
import numpy as np
from names_generator import generate_name

#### Data generation

This section collects student and subject details from the user and generates a random marks matrix using NumPy.

In [166]:
def generate_data():
    std_num = int(input("Enter number of students: "))
    std_names = generate_std_names(std_num)
    subjects = np.array(["Maths", "Physics", "Chemistry", "Biology", "Computer Science"])
    
    std_marks = np.random.randint(0, 101, size=(std_num, subjects.size)).reshape(std_num, subjects.size)
    
    return std_names, subjects, std_marks


def generate_std_names(n):
    std_names = []
    for i in range(n):
        name = generate_name()
        std_names.append(name)
    return np.array(std_names)


#### Analysis

This section performs statistical analysis on the marks matrix, including averages, toppers, weakest students, and subject-wise performance.

In [167]:
def calc_avg_std(marks):
    return np.mean(marks, axis=1)


def calc_avg_subj(marks):
    return np.mean(marks, axis=0)


def calc_class_avg(marks):
    return np.mean(marks)


def assign_grades(students_avg):
    grades = np.empty(shape=students_avg.shape, dtype=object)
    grades[students_avg >= 90] = "A+"
    grades[(students_avg >= 80) & (students_avg < 90)] = "A"
    grades[(students_avg >= 70) & (students_avg < 80)] = "B"
    grades[(students_avg >= 60) & (students_avg < 70)] = "C"
    grades[(students_avg >= 50) & (students_avg < 60)] = "D"
    grades[(students_avg >= 0) & (students_avg < 50)] = "F"
    return grades


def check_status(students_avg):
    status = np.where(students_avg < 50, "Fail", "Pass")
    return status


def calc_pass_percentage(status):
    pass_percentage = np.count_nonzero(status == "Pass") / status.size * 100
    return pass_percentage


def best_student(students_avg, std_names, grades):
    idx = np.argmax(students_avg)
    name = std_names[idx]
    highest_marks = students_avg[idx]
    grade = grades[idx]
    
    return name, highest_marks, grade


def worst_student(students_avg, std_names, grades):
    idx = np.argmin(students_avg)
    name = std_names[idx]
    lowest_marks = students_avg[idx]
    grade = grades[idx]
    
    return name, lowest_marks, grade


def best_subject(subjects_avg, names):
    idx = np.argmax(subjects_avg)
    name = names[idx]
    highest_marks = subjects_avg[idx]
    
    return name, highest_marks


def worst_subject(subjects_avg, names):
    idx = np.argmin(subjects_avg)
    name = names[idx]
    lowest_marks = subjects_avg[idx]
    
    return name, lowest_marks


#### Reporting

In [175]:
def generate_report(report_data):
    print("=" * 100)
    print(f"{f'STUDENT MARKS ANALYSIS REPORT':^100s}")
    print("=" * 100)
    
    print(f"\n{'Total Students':<18s} : {report_data["n_students"]}")
    print(f"{'Subjects':<18s} : {report_data["subjects"]}\n")
    print("-" * 100)
    
    print(f"{'Class Average':<18s} : {report_data["class_avg"]:.2f}% \n")
    print(f"{'Topper Student':<18s} : {report_data["top_student"]["name"]} -> {report_data["top_student"]["avg_marks"]:.2f}% ({report_data["top_student"]["grade"]})")
    print(f"{'Weakest Student':<18s} : {report_data["worst_student"]["name"]} -> {report_data["worst_student"]["avg_marks"]:.2f}% ({report_data["worst_student"]["grade"]})\n")
    print(f"{'Best Subject':<18s} : {report_data["best_subject"]["name"]} (avg: {report_data["best_subject"]["marks"]:.2f}%)")
    print(f"{'Toughest Subject':<18s} : {report_data["worst_subject"]["name"]} (avg: {report_data["worst_subject"]["marks"]:.2f}%)\n")
    print(f"{'Pass Percentage':<18s} : {report_data["pass_percentage"]:.2f}%")
    print("=" * 100)
    
    

#### Visualization

#### Execution pipeline

In [169]:
std_names, subj_names, std_marks = generate_data()
print(std_names)
print(subj_names)
print(std_marks)

['dreamy_perlman' 'beautiful_robinson' 'jolly_nobel' 'strange_haslett'
 'cranky_maxwell' 'busy_kalam' 'laughing_raman' 'eloquent_hamilton'
 'hardcore_ganguly' 'gracious_kirch' 'hungry_hertz' 'beautiful_faraday'
 'competent_williamson' 'friendly_newton' 'inspiring_goldberg'
 'epic_colden' 'affectionate_torvalds' 'romantic_colden']
['Maths' 'Physics' 'Chemistry' 'Biology' 'Computer Science']
[[18 14 30 19 80]
 [63  3 17 30 78]
 [66 43 79 15 73]
 [68 71 24 46 94]
 [30 51 95 99 95]
 [82 75 94 69 74]
 [26 38 34 10 99]
 [29 98  6 98 64]
 [53 29 73 14 49]
 [29 28 22 92 94]
 [53 17 69 64  8]
 [ 0 55 28 88 93]
 [11 80 84  1 47]
 [42 54 47 18 46]
 [92 85 60 23 67]
 [58 70 79 64 69]
 [88 37  8 25 27]
 [ 7 35 48 36 94]]


In [170]:
avg_std = calc_avg_std(std_marks)
avg_sub = calc_avg_subj(std_marks)

In [171]:
grades = assign_grades(avg_std)
print(grades)
status = check_status(avg_std)
print(status)
class_avg = calc_class_avg(std_marks)
print(class_avg)

['F' 'F' 'D' 'C' 'B' 'B' 'F' 'D' 'F' 'D' 'F' 'D' 'F' 'F' 'C' 'C' 'F' 'F']
['Fail' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass'
 'Fail' 'Pass' 'Fail' 'Fail' 'Pass' 'Pass' 'Fail' 'Fail']
51.74444444444445


In [172]:
name, marks = best_subject(avg_sub, subj_names)
best_subject = {
    "name": name,
    "marks": marks
}
print(name, marks)
name, marks = worst_subject(avg_sub, subj_names)
worst_subject = {
    "name": name,
    "marks": marks
}
print(name, marks)

Computer Science 69.5
Biology 45.05555555555556


In [173]:
status = check_status(std_marks)
print(status)
pass_percentage = calc_pass_percentage(status)
print(pass_percentage)
print()
name, marks, grade =  best_student(avg_std, std_names, grades)
top_student = {
    "name": name,
    "avg_marks": marks,
    "grade": grade 
}
print(name, marks, grade)

name, marks, grade =  worst_student(avg_std, std_names, grades)
worst_student = {
    "name": name,
    "avg_marks": marks,
    "grade": grade 
}
print(name, marks, grade)

[['Fail' 'Fail' 'Fail' 'Fail' 'Pass']
 ['Pass' 'Fail' 'Fail' 'Fail' 'Pass']
 ['Pass' 'Fail' 'Pass' 'Fail' 'Pass']
 ['Pass' 'Pass' 'Fail' 'Fail' 'Pass']
 ['Fail' 'Pass' 'Pass' 'Pass' 'Pass']
 ['Pass' 'Pass' 'Pass' 'Pass' 'Pass']
 ['Fail' 'Fail' 'Fail' 'Fail' 'Pass']
 ['Fail' 'Pass' 'Fail' 'Pass' 'Pass']
 ['Pass' 'Fail' 'Pass' 'Fail' 'Fail']
 ['Fail' 'Fail' 'Fail' 'Pass' 'Pass']
 ['Pass' 'Fail' 'Pass' 'Pass' 'Fail']
 ['Fail' 'Pass' 'Fail' 'Pass' 'Pass']
 ['Fail' 'Pass' 'Pass' 'Fail' 'Fail']
 ['Fail' 'Pass' 'Fail' 'Fail' 'Fail']
 ['Pass' 'Pass' 'Pass' 'Fail' 'Pass']
 ['Pass' 'Pass' 'Pass' 'Pass' 'Pass']
 ['Pass' 'Fail' 'Fail' 'Fail' 'Fail']
 ['Fail' 'Fail' 'Fail' 'Fail' 'Pass']]
51.11111111111111

busy_kalam 78.8 B
dreamy_perlman 32.2 F


In [174]:
report_data = {
    "n_students": len(std_names),
    "subjects": subj_names,
    "class_avg": class_avg,
    "top_student": top_student,
    "worst_student": worst_student,
    "best_subject": best_subject,
    "worst_subject": worst_subject,
    "pass_percentage": pass_percentage
}

generate_report(report_data)

                                   STUDENT MARKS ANALYSIS REPORT                                    

Total Students     : 18
Subjects           : ['Maths' 'Physics' 'Chemistry' 'Biology' 'Computer Science']

----------------------------------------------------------------------------------------------------
Class Average      : 51.74% 

Topper Student     : busy_kalam -> 78.80% (B)
Weakest Student    : dreamy_perlman -> 32.20% (F)

Best Subject       : Computer Science (avg: 69.50%)
Toughest Subject   : Biology (avg: 45.06%)

Pass Percentage    : 51.11%
