In [58]:
import numpy as np
from names_generator import generate_name

#### Data generation

This section collects student and subject details from the user and generates a random marks matrix using NumPy.

In [59]:
def generate_data():
    std_num = int(input("Enter number of students: "))
    std_names = generate_std_names(std_num)
    subjects = np.array(["Maths", "Physics", "Chemistry", "Biology", "Computer Science"])
    
    std_marks = np.random.randint(0, 101, size=(std_num, subjects.size)).reshape(std_num, subjects.size)
    
    return std_names, subjects, std_marks


def generate_std_names(n):
    std_names = []
    for i in range(n):
        name = generate_name()
        std_names.append(name)
    return np.array(std_names)


#### Analysis

This section performs statistical analysis on the marks matrix, including averages, toppers, weakest students, and subject-wise performance.

In [60]:
def avg_students(marks):
    return np.mean(marks, axis=1)


def avg_subjects(marks):
    return np.mean(marks, axis=0)


def assign_grades(marks):
    students_avg = avg_students(marks)
    
    grades = np.empty(shape=students_avg.shape, dtype=object)
    grades[students_avg >= 90] = "A+"
    grades[(students_avg >= 80) & (students_avg < 90)] = "A"
    grades[(students_avg >= 70) & (students_avg < 80)] = "B"
    grades[(students_avg >= 60) & (students_avg < 70)] = "C"
    grades[(students_avg >= 50) & (students_avg < 60)] = "D"
    grades[(students_avg >= 0) & (students_avg < 50)] = "F"
    
    return grades


def best_student(marks, std_names):
    students_avg = avg_students(marks)
    idx = np.argmax(students_avg)
    name = std_names[idx]
    highest_marks = students_avg[idx]
    
    return np.array([name, highest_marks])


def worst_student(marks, std_names):
    students_avg = avg_students(marks)
    idx = np.argmin(students_avg)
    name = std_names[idx]
    lowest_marks = students_avg[idx]
    
    return np.array([name, lowest_marks])


def best_subject(marks, names):
    subjects_avg = avg_subjects(marks)
    idx = np.argmax(subjects_avg)
    name = names[idx]
    highest_marks = subjects_avg[idx]
    
    return np.array([name, highest_marks])


def worst_subject(marks, names):
    avg_marks = avg_subjects(marks)
    idx = np.argmin(avg_marks)
    name = names[idx]
    lowest_marks = avg_marks[idx]
    
    return np.array([name, lowest_marks])


In [61]:

std_names, subj_names, std_marks = generate_data()
print(std_names)
print(subj_names)
print(std_marks)

['magical_hofstadter' 'magical_archimedes' 'infallible_mclean'
 'silly_keller' 'practical_gates' 'magical_diffie' 'eager_bose'
 'funny_galois' 'modest_nash' 'great_moore' 'affectionate_ride'
 'hopeful_benz' 'boring_varahamihira' 'trusting_bouman'
 'admiring_chebyshev' 'vibrant_gould' 'quizzical_chatelet'
 'mystifying_allen' 'friendly_nightingale' 'pensive_moore']
['Maths' 'Physics' 'Chemistry' 'Biology' 'Computer Science']
[[ 33  76  12  10  26]
 [ 70  39  20  13  90]
 [ 62   2  38  98  22]
 [ 28   0  36  43  85]
 [100  56  93  55  97]
 [ 72  20   2  77  78]
 [ 97  27  35  77  81]
 [ 57   9  60  91  13]
 [ 69  80  64  71  34]
 [ 96  79  88  22  39]
 [  4   5  93  37  39]
 [ 37  51  75  15  72]
 [ 60  12  89  59  22]
 [ 48  38  54  32  36]
 [ 15  11  81  61  35]
 [ 47  27  22  36  45]
 [ 54  40  57  72  18]
 [ 59  82  84  19  91]
 [  0   9   1  66   8]
 [ 29  93   7   9  72]]


In [62]:
print(avg_students(std_marks))
print(assign_grades(std_marks))
print(avg_subjects(std_marks))

[31.4 46.4 44.4 38.4 80.2 49.8 63.4 46.  63.6 64.8 35.6 50.  48.4 41.6
 40.6 35.4 48.2 67.  16.8 42. ]
['F' 'F' 'F' 'F' 'A' 'F' 'C' 'F' 'C' 'C' 'F' 'D' 'F' 'F' 'F' 'F' 'F' 'C'
 'F' 'F']
[51.85 37.8  50.55 48.15 50.15]


In [63]:
print(best_student(std_marks, std_names))
print(worst_student(std_marks, std_names))
print(best_subject(std_marks, subj_names))
print(worst_subject(std_marks, subj_names))

['practical_gates' '80.2']
['friendly_nightingale' '16.8']
['Maths' '51.85']
['Physics' '37.8']


#### Reporting

#### Visualization

#### Execution pipeline