In [43]:
import numpy as np

#### Data generation

This section collects student and subject details from the user and generates a random marks matrix using NumPy.

In [44]:
def generate_data():
    std_num = int(input("Enter number of students: "))
    subj_num = int(input("Enter number of subjects: "))
    
    std_names = collect_std_names(std_num)
    subj_names = collect_subj_names(subj_num)
    
    std_marks = np.random.randint(0, 101, size=(std_num, subj_num)).reshape(std_num, subj_num)
    
    return std_names, subj_names, std_marks


def collect_std_names(n):
    std_names = []
    for i in range(n):
        name = input(f"Enter name of student {i+1}: ").strip().title()
        std_names.append(name)
    return np.array(std_names)


def collect_subj_names(n):
    subj_names = []
    for i in range(n):
        subj = input(f"Enter subject {i+1}: ").strip().title()
        subj_names.append(subj)
    return np.array(subj_names)

#### Analysis

This section performs statistical analysis on the marks matrix, including averages, toppers, weakest students, and subject-wise performance.

In [53]:
def avg_students(marks):
    return np.mean(marks, axis=1)


def avg_subjects(marks):
    return np.mean(marks, axis=0)


def grading_sys(marks):
    students_avg = avg_students(marks)
    
    grades = np.empty(shape=students_avg.shape, dtype=object)
    grades[students_avg >= 90] = "A+"
    grades[(students_avg >= 80) & (students_avg < 90)] = "A"
    grades[(students_avg >= 70) & (students_avg < 80)] = "B"
    grades[(students_avg >= 60) & (students_avg < 70)] = "C"
    grades[(students_avg >= 50) & (students_avg < 60)] = "D"
    grades[(students_avg >= 0) & (students_avg < 50)] = "F"
    
    return grades


def best_student(marks, std_names):
    students_avg = avg_students(marks)
    idx = np.argmax(students_avg)
    name = std_names[idx]
    highest_marks = students_avg[idx]
    
    return np.array([name, highest_marks])


def worst_student(marks, std_names):
    students_avg = avg_students(marks)
    idx = np.argmin(students_avg)
    name = std_names[idx]
    lowest_marks = students_avg[idx]
    
    return np.array([name, lowest_marks])


def best_subject(marks, names):
    subjects_avg = avg_subjects(marks)
    idx = np.argmax(subjects_avg)
    name = names[idx]
    highest_marks = subjects_avg[idx]
    
    return np.array([name, highest_marks])


def worst_subject(marks, names):
    avg_marks = avg_subjects(marks)
    idx = np.argmin(avg_marks)
    name = names[idx]
    lowest_marks = avg_marks[idx]
    
    return np.array([name, lowest_marks])


In [ ]:

std_names, subj_names, std_marks = generate_data()
print(std_names)
print(subj_names)
print(std_marks)

['RJ' 'DImple']
['Maths' 'ENglish' 'Science']
[[14 53 32]
 [69 43 29]]


In [54]:
print(avg_students(std_marks))
print(grading_sys(std_marks))
print(avg_subjects(std_marks))

[33. 47.]
['F' 'F']
[41.5 48.  30.5]


In [47]:
print(best_student(std_marks, std_names))
print(worst_student(std_marks, std_names))
print(best_subject(std_marks, subj_names))
print(worst_subject(std_marks, subj_names))

['DImple' '47.0']
['RJ' '33.0']
['ENglish' '48.0']
['Science' '30.5']


#### Reporting

#### Visualization

#### Execution pipeline