In [1]:
import numpy as np

#### Data generation

This section collects student and subject details from the user and generates a random marks matrix using NumPy.

In [ ]:
def generate_data():
    std_num = int(input("Enter number of students: "))
    subj_num = int(input("Enter number of subjects: "))
    
    std_names = collect_std_names(std_num)
    subj_names = collect_subj_names(subj_num)
    
    std_marks = np.random.randint(0, 101, size=(std_num, subj_num)).reshape(std_num, subj_num)
    
    return std_names, subj_names, std_marks


def collect_std_names(n):
    std_names = []
    for i in range(n):
        name = input(f"Enter name of student {i+1}: ").strip().title()
        std_names.append(name)
    return np.array(std_names)


def collect_subj_names(n):
    subj_names = []
    for i in range(n):
        subj = input(f"Enter subject {i+1}: ").strip().title()
        subj_names.append(subj)
    return np.array(subj_names)

#### Analysis

This section performs statistical analysis on the marks matrix, including averages, toppers, weakest students, and subject-wise performance.

In [41]:
def avg_marks_per_std(std_marks):
    return np.mean(std_marks, axis=1)


def avg_marks_per_subj(std_marks):
    return np.mean(std_marks, axis=0)


def grading_sys(std_marks):
    return 


def topper_std(std_marks, std_names):
    avg_std_marks = avg_marks_per_std(std_marks)
    idx = np.argmax(avg_std_marks)
    std_name = std_names[idx]
    std_marks = avg_std_marks[idx]
    
    return np.array([std_name, std_marks])


def weakest_std(std_marks, std_names):
    avg_std_marks = avg_marks_per_std(std_marks)
    idx = np.argmin(avg_std_marks)
    std_name = std_names[idx]
    std_marks = avg_std_marks[idx]
    
    return np.array([std_name, std_marks])


def best_subj(std_marks, subj_names):
    avg_subj_marks = avg_marks_per_subj(std_marks)
    idx = np.argmax(avg_subj_marks)
    subj_name = subj_names[idx]
    subj_marks = avg_subj_marks[idx]
    
    return np.array([subj_name, subj_marks])


def toughest_subj(std_marks, subj_names):
    avg_subj_marks = avg_marks_per_subj(std_marks)
    idx = np.argmin(avg_subj_marks)
    subj_name = subj_names[idx]
    subj_marks = avg_subj_marks[idx]
    
    return np.array([subj_name, subj_marks])


In [37]:
std_names, subj_names, std_marks = generate_data()
print(std_names)
print(subj_names)
print(std_marks)

['RJ' 'DImple']
['Maths' 'ENglish' 'Science']
[[14 53 32]
 [69 43 29]]


In [42]:
print(topper_std(std_marks, std_names))
print(weakest_std(std_marks, std_names))
print(best_subj(std_marks, subj_names))
print(toughest_subj(std_marks, subj_names))

['DImple' '47.0']
['RJ' '33.0']
['ENglish' '48.0']
['Science' '30.5']


In [14]:
avg_marks_per_subj(std_marks)

array([45.3, 48.5, 51.6, 47.1, 56.7])

#### Reporting

#### Visualization

#### Execution pipeline